In [0]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


data = pd.read_excel('Data_Train.xlsx', index_col=0)

data_test = pd.read_excel('Data_Test.xlsx', index_col=0)

data=data.values[:,2:8]

print(data_test.values[:,2:8])

data_test=data_test.values[:,2:8]

#Data Cleaning and preprocessing

for i in range(data.shape[0]):
    data[i,0]=data[i,0].replace('₹', '')
    data[i,1]=data[i,1].replace('₹', '')
    data[i,2]=data[i,2].replace('-', '0')
    data[i,3]=data[i,3].replace('-', '0')
    data[i,4]=data[i,4].replace('-', '0')
    data[i,2]=data[i,2].replace('NEW', '0')
    data[i,5]=data[i,5].replace(' minutes', '')

    data[i,0]=data[i,0].replace(',', '')
    data[i,1]=data[i,1].replace(',', '')
    data[i,2]=data[i,2].replace(',', '')
    data[i,2]=data[i,2].replace('Opening Soon', '0')
    data[i,0]=data[i,0].replace('for', '0')
    data[i,2]=data[i,2].replace('Temporarily Closed', '0')

datat=data_test

for i in range(datat.shape[0]):
    datat[i,0]=datat[i,0].replace('₹', '')
    datat[i,1]=datat[i,1].replace('₹', '')
    datat[i,2]=datat[i,2].replace('-', '0')
    datat[i,3]=datat[i,3].replace('-', '0')
    datat[i,4]=datat[i,4].replace('-', '0')
    datat[i,2]=datat[i,2].replace('NEW', '0')
    #datat[i,5]=datat[i,5].replace(' minutes', '')

    datat[i,0]=datat[i,0].replace(',', '')
    datat[i,1]=datat[i,1].replace(',', '')
    datat[i,2]=datat[i,2].replace(',', '')
    datat[i,2]=datat[i,2].replace('Opening Soon', '0')
    datat[i,0]=datat[i,0].replace('for', '0')
    datat[i,2]=datat[i,2].replace('Temporarily Closed', '0')    
    


for i in range(data.shape[0]):
    
    for j in range(data.shape[1]):
        
        data[i,j] = float(data[i,j])
        
for i in range(datat.shape[0]):
    
    for j in range(datat.shape[1]):
        
        datat[i,j] = float(datat[i,j])
        

X = data[:,0:5]
Y = data[:,5]
Xt = datat[:,0:5]
print(X,"\n",Y,"\n",Xt)

[['₹350' '₹50' '4.2' '361' '225']
 ['₹100' '₹50' 'NEW' '-' '-']
 ['₹100' '₹50' '3.6' '36' '16']
 ...
 ['₹150' '₹50' '3.0' '16' '1']
 ['₹100' '₹99' '3.0' '7' '2']
 ['₹150' '₹50' '3.6' '99' '30']]
[[200.0 50.0 3.5 12.0 4.0]
 [100.0 50.0 3.5 11.0 4.0]
 [150.0 50.0 3.6 99.0 30.0]
 ...
 [100.0 50.0 3.5 45.0 18.0]
 [100.0 50.0 3.1 24.0 9.0]
 [100.0 50.0 0.0 0.0 0.0]] 
 [30.0 30.0 65.0 ... 30.0 30.0 30.0] 
 [[350.0 50.0 4.2 361.0 225.0]
 [100.0 50.0 0.0 0.0 0.0]
 [100.0 50.0 3.6 36.0 16.0]
 ...
 [150.0 50.0 3.0 16.0 1.0]
 [100.0 99.0 3.0 7.0 2.0]
 [150.0 50.0 3.6 99.0 30.0]]


In [0]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X = sc.fit_transform(X)

Xt = sc.transform(Xt)


Y = Y.reshape((len(Y), 1)) 

Y = sc.fit_transform(Y)

Y = Y.ravel()


In [0]:
#Model Building
from sklearn.ensemble import GradientBoostingRegressor

gbr=GradientBoostingRegressor( loss = 'huber',learning_rate=0.001,n_estimators=350, max_depth=6 , subsample=1,  verbose=False,random_state=126)  
gbr.fit(X, Y)



GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.001, loss='huber', max_depth=6,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=350,
                          n_iter_no_change=None, presort='auto',
                          random_state=126, subsample=1, tol=0.0001,
                          validation_fraction=0.1, verbose=False,
                          warm_start=False)

In [0]:
#Prediction for test data 
y_pred_gbr = sc.inverse_transform(gbr.predict(Xt))
y1=y_pred_gbr.astype(int) 
y1=y1.astype(int).astype(str) 
for i in range(len(y1)):
    y1[i] = y1[i]+" minutes"

In [0]:
#Sending output to Excel file
df = pd.DataFrame (y1)
print(df.head)
df.to_excel("GradientBoostingRegressor.xlsx", index = False)

<bound method NDFrame.head of                0
0     32 minutes
1     30 minutes
2     30 minutes
3     31 minutes
4     31 minutes
...          ...
2769  30 minutes
2770  30 minutes
2771  30 minutes
2772  32 minutes
2773  31 minutes

[2774 rows x 1 columns]>
